version: '3.3'

services:
  zabbix-proxy-mysql:
    image: mariadb:10.5
    container_name: enocta-istanbul-zabbix-proxy-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ClnrMON2018!
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix_proxy
    volumes:
      - /opt/zabbix/mysql-data:/var/lib/mysql
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-proxy:
    image: zabbix/zabbix-proxy-mysql:ubuntu-7.0-latest
    privileged: true
    container_name: enocta-istanbul-zabbix-proxy
    environment:
      - ZBX_HOSTNAME=enocta-istanbul-zabbix-proxy
      - ZBX_SERVER_HOST=monser.eclit.cloud:8080
      - DB_SERVER_HOST=enocta-istanbul-zabbix-proxy-mysql
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix_proxy
      - ZBX_TIMEOUT=30
      - ZBX_TLSCONNECT=psk
      - ZBX_TLSPSKIDENTITY=enocta-istanbul-zabbix-proxy
      - ZBX_TLSPSKFILE=/var/lib/zabbix/enc/zabbix_proxy.psk
      - ZBX_STARTPOLLERS=200
      - ZBX_STARTPINGERS=100
      - ZBX_STARTPOLLERSUNREACHABLE=30
      - ZBX_CACHESIZE=1G
      - ZBX_ENABLE_SNMP_TRAPS=true
      - ZBX_CONFIGFREQUENCY=60
      - ZBX_STARTTRAPPERS=100
      - ZBX_STARTPREPROCESSORS=100
    volumes:
      - /etc/zabbix/proxy.psk:/var/lib/zabbix/enc/zabbix_proxy.psk
      - /opt/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - /etc/zabbix/scripts:/usr/lib/zabbix/externalscripts:rw
    networks:
      - zabbix-network
    ports:
      - "10051:10051" # Zabbix Proxy port
    depends_on:
      - zabbix-proxy-mysql
    entrypoint: >
      sh -c "
      mkdir -p /var/lib/apt/lists/partial &&
      chmod -R 755 /var/lib/apt/lists &&
      apt update &&
      apt install -y python3 python3-pip python3-venv &&
      python3 -m venv /opt/zabbix-env &&
      source /opt/zabbix-env/bin/activate &&
      pip install urllib3==1.25.11 pyvmomi==7.0.3 requests==2.22 cryptography==3.4.8 py-zabbix python-dateutil pywbem purestorage &&
      /usr/bin/supervisord"
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-7.0-latest
    container_name: enocta-istanbul-zabbix-snmptraps
    volumes:
      - /opt/zabbix/snmptraps:/var/lib/zabbix/snmptraps
    networks:
      - zabbix-network
    ports:
      - "162:162/udp" # Published port for SNMP traps
    restart: unless-stopped

networks:
  zabbix-network:
    driver: bridge
